# Generated by Django 6.1.1 on 2026-09-06 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('POTHOLE', 'Pothole'), ('GARBAGE', 'Garbage / Waste'), ('STREETLIGHT', 'Streetlight'), ('DRAINAGE', 'Drainage'), ('WATER_LEAKAGE', 'Water Leakage'), ('ROAD_DAMAGE', 'Road Damage'), ('ILLEGAL_DUMPING', 'Illegal Dumping'), ('OTHER', 'Other')], max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address_text', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolution_photo', models.ImageField(blank=True, null=True, upload_to='resolution_photos/')),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
